#requires -Version 5.1
<#
.SYNOPSIS
    Run the TCPK detection benchmark and score it into precision / recall.

.DESCRIPTION
    Drives a curated corpus of fixtures (bench/corpus/<case>) against a VERIFIED
    expectations manifest (bench/expectations.json) and measures, per check:

      detect[]  rule-id regexes that SHOULD fire on this fixture (planted vulns)
      forbid[]  rule-id regexes that must NOT fire (clean / placeholder fixtures)

    Scoring (at the rule-id granularity):
      TP  a detect[] regex matched a finding      (caught the planted bug)
      FN  a detect[] regex matched nothing        (missed it)
      FP  a forbid[] regex matched a finding      (false positive)
      TN  a forbid[] regex matched nothing        (correctly stayed quiet)

      precision = TP / (TP + FP)      recall = TP / (TP + FN)

    Writes a Markdown scorecard (bench/SCORECARD.md by default) and returns a
    result object. Every expected rule-id is verified against the live check, so
    this is a regression gate, not a vanity number.

.EXAMPLE
    .\bench\Invoke-TcpkBenchmark.ps1
    Run with defaults; regenerate SCORECARD.md.
#>
[CmdletBinding()]
param(
    [string]$CorpusRoot,
    [string]$Manifest,
    [string]$OutFile,
    [double]$MinPrecision = 1.0,
    [double]$MinRecall = 1.0
)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSCommandPath
if (-not $CorpusRoot) { $CorpusRoot = Join-Path $root 'corpus' }
if (-not $Manifest)   { $Manifest   = Join-Path $root 'expectations.json' }
if (-not $OutFile)    { $OutFile    = Join-Path $root 'SCORECARD.md' }

# bench/ is a sibling of the TCPK/ module dir
$repo = Split-Path -Parent $root
Import-Module (Join-Path $repo 'TCPK\TCPK.psd1') -Force | Out-Null

# NB: in PS 5.1 ConvertFrom-Json emits a top-level JSON array as a SINGLE pipeline object,
# so wrapping it in @() yields a 1-element array containing the array. Assign directly and
# let foreach unroll it.
$cases = Get-Content -LiteralPath $Manifest -Raw | ConvertFrom-Json
$rows = New-Object System.Collections.Generic.List[object]
$TP = 0; $FP = 0; $FN = 0; $TN = 0

foreach ($c in $cases) {
    $dir = Join-Path $CorpusRoot $c.dir
    $ruleIds = @()
    try { $ruleIds = @(& $c.check -Path $dir | ForEach-Object { "$($_.RuleId)" } | Sort-Object -Unique) } catch { }
    $cTP = 0; $cFP = 0; $cFN = 0; $cTN = 0; $notes = @()
    foreach ($d in @($c.detect)) {
        if (@($ruleIds | Where-Object { $_ -match $d }).Count) { $cTP++ } else { $cFN++; $notes += "MISSED $d" }
    }
    foreach ($f in @($c.forbid)) {
        if (@($ruleIds | Where-Object { $_ -match $f }).Count) { $cFP++; $notes += "FALSE-POSITIVE $f" } else { $cTN++ }
    }
    $TP += $cTP; $FP += $cFP; $FN += $cFN; $TN += $cTN
    $rows.Add([pscustomobject]@{
        Case = "$($c.case)"; Check = "$($c.check)"; TP = $cTP; FP = $cFP; FN = $cFN; TN = $cTN
        Detected = ($ruleIds -join ', '); Notes = ($notes -join '; ')
    })
}

$prec = if (($TP + $FP) -gt 0) { [math]::Round($TP / ($TP + $FP), 3) } else { 1.0 }
$rec  = if (($TP + $FN) -gt 0) { [math]::Round($TP / ($TP + $FN), 3) } else { 1.0 }

$L = New-Object System.Collections.Generic.List[string]
$L.Add("# TCPK Detection Benchmark -- Scorecard")
$L.Add("")
$L.Add("Generated by ``bench/Invoke-TcpkBenchmark.ps1`` over $(@($cases).Count) curated fixtures.")
$L.Add("Every expected rule-id is verified against the live check (see ``bench/expectations.json``).")
$L.Add("")
$L.Add("- **Precision: $prec**  (TP / (TP + FP) -- of what it flagged, how much was real)")
$L.Add("- **Recall: $rec**  (TP / (TP + FN) -- of the planted bugs, how many it caught)")
$L.Add("- Tallies: TP=$TP  FP=$FP  FN=$FN  TN=$TN")
$L.Add("")
$L.Add("| Case | Check | TP | FP | FN | TN | Notes |")
$L.Add("|------|-------|----|----|----|----|-------|")
foreach ($r in $rows) { $L.Add("| $($r.Case) | $($r.Check) | $($r.TP) | $($r.FP) | $($r.FN) | $($r.TN) | $($r.Notes) |") }
$L.Add("")
$L.Add("Scope note: the corpus currently covers text/JS-scanned checks (Electron config + cert")
$L.Add("validation, secret scanning). Binary-scanned checks (crypto misuse, cleartext schemes, PE")
$L.Add("hardening, IL callsites) need compiled fixtures and are tracked as a follow-on expansion.")
[IO.File]::WriteAllText($OutFile, (($L -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding($false)))

[pscustomobject]@{
    Cases = @($cases).Count; TP = $TP; FP = $FP; FN = $FN; TN = $TN
    Precision = $prec; Recall = $rec; Rows = $rows; Scorecard = $OutFile
    Pass = ($prec -ge $MinPrecision -and $rec -ge $MinRecall)
}
